import os
BASE = r'c:\Users\BalagurovAI\Documents\GitHub\lomo\FG300C_5x'
CR = b'\r\n'
p = os.path.join(BASE, 'LOMO_FG300C.tcl')
b = open(p, 'rb').read()
def rep(b, old, new, tag):
    n = b.count(old)
    assert n == 1, tag + ': ' + str(n)
    return b.replace(old, new)

# 1. arc handler -> motion-type based
old = CR.join([
    b'proc PB_CMD__rotc_arc_handle { } {',
    b'#=============================================================',
    b'  global mom_ude_interpolation_lock',
    b'  if { ![info exists mom_ude_interpolation_lock] || $mom_ude_interpolation_lock != "Yes" } {',
    b'     return 0',
    b'  }',
    b'',
    b'  global mom_pos_arc_center mom_arc_radius mom_arc_direction',
    b'  global pb_lock_arc_active pb_lock_arc_radius pb_lock_turn_sign',
    b'',
    b'  set cx [expr $mom_pos_arc_center(0)]',
    b'  set cy [expr $mom_pos_arc_center(1)]',
    b'  set tol 0.5',
    b'',
    b'  if { ![info exists pb_lock_arc_active] } { set pb_lock_arc_active 0 }',
    b'',
    b'  if { [expr abs($cx)] < $tol && [expr abs($cy)] < $tol } {',
    b'     # Working arc whose center is on the C axis (0,0): the whole circle is the',
    b'     # rotary-table pass. Output the single C rotation once on its first arc and',
    b'     # swallow all remaining arcs of the circle.',
    b'     if { $pb_lock_arc_active == 0 } {',
    b'        set pb_lock_arc_active 1',
    b'        set pb_lock_arc_radius $mom_arc_radius',
    b'        set pb_lock_turn_sign -1',
    b'        if { [info exists mom_arc_direction] && $mom_arc_direction == "CCLW" } {',
    b'           set pb_lock_turn_sign 1',
    b'        }',
    b'        PB_CMD__rotc_turn_block',
    b'     }',
    b'     return 1',
    b'  }',
    b'',
    b'  # Arc with a different center (engage approach / retract departure).',
    b'  # The literal C=IC(...) block does not update the post motion-G state,',
    b'  # so force G2/G3 so the retract arc starts with a circular code.',
    b'  if { $pb_lock_arc_active == 1 } {',
    b'     MOM_force Once G_motion',
    b'     set pb_lock_arc_active 0',
    b'  }',
    b'  return 0',
    b'}',
]) + CR
new = CR.join([
    b'proc PB_CMD__rotc_arc_handle { } {',
    b'#=============================================================',
    b'# Interpolation-lock (rotary-table C) arc handling:',
    b'#   - the engage arc sets the turn sign (CCLW -> + internal, CLW -> - external);',
    b'#   - the working circle (CUT arc) is replaced by the single rotary C turn.',
    b'  global mom_ude_interpolation_lock',
    b'  if { ![info exists mom_ude_interpolation_lock] || $mom_ude_interpolation_lock != "Yes" } {',
    b'     return 0',
    b'  }',
    b'',
    b'  global mom_arc_direction mom_motion_type',
    b'  global pb_lock_turn_sign pb_lock_turn_done',
    b'  if { ![info exists pb_lock_turn_done] } { set pb_lock_turn_done 0 }',
    b'',
    b'  if { [info exists mom_arc_direction] } {',
    b'     if { $mom_arc_direction == "CCLW" } { set pb_lock_turn_sign 1 } else { set pb_lock_turn_sign -1 }',
    b'  }',
    b'',
    b'  if { [info exists mom_motion_type] } {',
    b'     if { $mom_motion_type == "CUT" || $mom_motion_type == "FIRSTCUT" || $mom_motion_type == "STEPOVER" } {',
    b'        if { $pb_lock_turn_done == 0 } {',
    b'           set pb_lock_turn_done 1',
    b'           PB_CMD__rotc_turn_block',
    b'        }',
    b'        return 1',
    b'     }',
    b'  }',
    b'',
    b'  # The retract arc after the rotation must restart with G2/G3 (the literal',
    b'  # G1 C=IC(...) block does not update the post motion-G state).',
    b'  if { $pb_lock_turn_done == 1 } {',
    b'     MOM_force Once G_motion',
    b'  }',
    b'  return 0',
    b'}',
]) + CR
b = rep(b, old, new, 'arc')

# 2. linear handler -> motion-type based
old = CR.join([
    b'proc PB_CMD__rotc_linear_cut { } {',
    b'#=============================================================',
    b'# Interpolation-lock (rotary-table C) mode.',
    b'# The working contour arrives as many SMALL LINEAR XY moves that trace a full',
    b'# circle about the C-axis (centre approx (0,0)) at a nearly constant radius and',
    b'# at constant Z.  We replace that whole XY run-around with a single rotary C move:',
    b'#     G1 C=IC(360.1) F200',
    b'# (no G90 needed - C=IC keeps the absolute G90 mode).',
    b'# Returns 1 if the current linear move was consumed (rotary output emitted, XY',
    b'# linear suppressed); returns 0 if the move should be output normally.',
    b'   global mom_ude_interpolation_lock',
    b'   if { ![info exists mom_ude_interpolation_lock] || $mom_ude_interpolation_lock != "Yes" } {',
    b'      return 0',
    b'   }',
    b'   global mom_mcs_goto',
    b'   if { ![info exists mom_mcs_goto] } {',
    b'      return 0',
    b'   }',
    b'',
    b'   global pb_lock_cut_active pb_lock_cut_r pb_lock_prev_r pb_lock_prev_z',
    b'   global pb_lock_prev_x pb_lock_prev_y pb_lock_turn_sign',
    b'',
    b'   if { ![info exists pb_lock_cut_active] } { set pb_lock_cut_active 0 }',
    b'   if { ![info exists pb_lock_prev_r] }   { set pb_lock_prev_r  -1.0 }',
    b'   if { ![info exists pb_lock_prev_z] }   { set pb_lock_prev_z  0.0 }',
    b'   if { ![info exists pb_lock_prev_x] }   { set pb_lock_prev_x  0.0 }',
    b'   if { ![info exists pb_lock_prev_y] }   { set pb_lock_prev_y  0.0 }',
    b'',
    b'   set x [expr $mom_mcs_goto(0)]',
    b'   set y [expr $mom_mcs_goto(1)]',
    b'   set z [expr $mom_mcs_goto(2)]',
    b'   if { [catch {set r [expr hypot($x,$y)]}] } { set r 0.0 }',
    b'   set dZ [expr abs($z - $pb_lock_prev_z)]',
    b'',
    b'   if { $pb_lock_cut_active == 0 } {',
    b'      # --- Not yet in a flat full-circle pass on C axis ---',
    b'      if { $pb_lock_prev_r >= 0 && $dZ < 0.001 && $r > 0.5 } {',
    b'         if { [expr abs($r - $pb_lock_prev_r)] < 0.2 } {',
    b'            # Just entered a flat run at (almost) constant radius around (0,0)',
    b'            set pb_lock_cut_active 1',
    b'            set pb_lock_cut_r $r',
    b'            set pb_lock_turn_sign -1',
    b'            if { [expr $pb_lock_prev_x * $y - $pb_lock_prev_y * $x] > 0 } {',
    b'               set pb_lock_turn_sign 1',
    b'            }',
    b'            PB_CMD_output_comment ";Cutting"',
    b'            PB_CMD__rotc_turn_block',
    b'         }',
    b'      }',
    b'      set pb_lock_prev_r $r',
    b'      set pb_lock_prev_z $z',
    b'      set pb_lock_prev_x $x',
    b'      set pb_lock_prev_y $y',
    b'      if { $pb_lock_cut_active } { return 1 }',
    b'      return 0',
    b'   } else {',
    b'      # --- Inside the flat full-circle pass ---',
    b'      # A Z change signals the end of the flat rotary cut (helical out).',
    b'      if { $dZ > 0.01 } {',
    b'         set pb_lock_cut_active 0',
    b'         set pb_lock_prev_r $r',
    b'         set pb_lock_prev_z $z',
    b'         set pb_lock_prev_x $x',
    b'         set pb_lock_prev_y $y',
    b'         return 0',
    b'      }',
    b'      # Still on the same flat radius: consume this XY move (table rotates already)',
    b'      if { [expr abs($r - $pb_lock_cut_r)] < 0.8 } {',
    b'         set pb_lock_prev_r $r',
    b'         set pb_lock_prev_z $z',
    b'         set pb_lock_prev_x $x',
    b'         set pb_lock_prev_y $y',
    b'         return 1',
    b'      }',
    b'      # Left the circle radius -> stop rotary pass',
    b'      set pb_lock_cut_active 0',
    b'      set pb_lock_prev_r $r',
    b'      set pb_lock_prev_z $z',
    b'      set pb_lock_prev_x $x',
    b'      set pb_lock_prev_y $y',
    b'      return 0',
    b'   }',
    b'}',
]) + CR
new = CR.join([
    b'proc PB_CMD__rotc_linear_cut { } {',
    b'#=============================================================',
    b'# Interpolation-lock (rotary-table C) linear handling:',
    b'# the working circle (CUT linear moves) is replaced by the single rotary C turn.',
    b'   global mom_ude_interpolation_lock',
    b'   if { ![info exists mom_ude_interpolation_lock] || $mom_ude_interpolation_lock != "Yes" } {',
    b'      return 0',
    b'   }',
    b'',
    b'   global mom_motion_type',
    b'   global pb_lock_turn_done',
    b'   if { ![info exists pb_lock_turn_done] } { set pb_lock_turn_done 0 }',
    b'',
    b'   if { [info exists mom_motion_type] } {',
    b'      if { $mom_motion_type == "CUT" || $mom_motion_type == "FIRSTCUT" || $mom_motion_type == "STEPOVER" } {',
    b'         if { $pb_lock_turn_done == 0 } {',
    b'            set pb_lock_turn_done 1',
    b'            PB_CMD__rotc_turn_block',
    b'         }',
    b'         return 1',
    b'      }',
    b'   }',
    b'   return 0',
    b'}',
]) + CR
b = rep(b, old, new, 'linear')

# 3. reset pb_lock_turn_done per operation
b = rep(b,
    b'  global mom_ude_interpolation_lock mom_siemens_ori_def pb_lock_arc_active' + CR,
    b'  global mom_ude_interpolation_lock mom_siemens_ori_def pb_lock_arc_active pb_lock_turn_done' + CR,
    'reset-g')
b = rep(b,
    b'     set pb_lock_arc_active 0' + CR,
    b'     set pb_lock_arc_active 0' + CR + b'     set pb_lock_turn_done 0' + CR,
    'reset-s')

assert b.count(b'\n') == b.count(b'\r'), 'mixed line endings'
assert max(b) < 128, 'non-ASCII byte'
open(p, 'wb').write(b)
print('patched', len(b))
print('ALL DONE')
